### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by ElisaGDR** [4GeeksAcademy/iirenevs-modelo-datos-starwars#1]
Buen trabajo @iireneVS , te sugiero algunos cambios: 

- En `CharacterFavorites` debes cambiar a plural `character.id`, debería ser `charactes.id` . (línea 62)
- Lo mismo pasa en línea 71 con `planet.id` 
- Linea 67 `Planet_favorites` está con la P en mayúsculas, debería ser minúscula.

**Comment by iireneVS** [comment]
Voy a corregirlo!! Gracias!!
